fixed folder path issue of 'font-awesome'
Running "grunt package" command from terminal was generating following error. 

------------------------------------------
Running "less:dev" (less) task
>> FileError: '../../../bower_components/font-Awesome/less/variables.less' wasn't found in src/less/font-awesome/_index.less on line 3, column 1:
>> 2 
>> 3 @import "@{font-awesome-path}/variables.less";
>> 4 @import "@{font-awesome-path}/mixins.less";
Warning: Error compiling src/less/_index.less Use --force to continue.

Aborted due to warnings.
----------------------------------------------

I have replaced "font-Awesome" to "font-awesome"